version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: backend_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: horus_aan_db
      TZ: Asia/Jakarta
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
